<h3>Views Over Time <img height="25" width="25" class="number-spinner" id="views-over-time-spinner" src="/img/ajax_spinner.GIF" alt="Loading"/></h3>
<div class="chartMargin">
    <label for="date_start">Start date:</label><input type="date" id="date_start" name="date_start" value="<?php echo date('Y-m-d', strtotime(date('Y-m-d') . '-1 year')); ?>" style="margin-right: 50px">
    <label for="date_end">Final date:</label><input type="date" id="date_end" name="date_end" value="<?php echo date('Y-m-d'); ?>" max="<?php echo date('Y-m-d'); ?>" style="margin-right: 50px">

    <div class="chartContainer" style="width: 1090px; height: 510px;">
        <span class="graph_status" id="view_over_time_status">Loading Views over Time chart...</span>
        <div id="views-over-time-graphic" style="width: 1080px; height: 500px;">

        </div>
    </div>
</div>