<div>
    <h2>Real-Time Data <img height="25" width="25" class="number-spinner" id="real-time-pixel-spinner" src="/img/ajax_spinner.GIF" alt="Loading"/></h2>
</div>
<div id="real-time" class="hide-overflow">

    <div class="blockId">
        <div id="impressions">
            <div class="actualNumber">
                <div class="numberType">
                    <div class="numberTitleBlock">
                        <span class="numberTitle centerText">Pixel Views</span>
                    </div>
                    <div>
                        <span id="pixel_count" class="number centerText">
                            <?php
                            echo $pixels;
                            ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>