<?php
$this->headLink()
        ->appendStylesheet($this->basePath() . '/css/search/form.css')
        ->appendStylesheet($this->basePath() . '/css/search/results.css');
$this->headScript()
        ->appendFile($this->basePath() . '/js/search/search.js');
$title = "Search our database";
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
echo $this->form()->openTag($form);

echo '<div class="blockInputSearch">';
echo '<div class="blockLabel">';
echo $this->formLabel($form->get('urlsearch'));
echo '</div>';
echo $this->formElement($form->get('urlsearch'));
echo $this->formElementErrors($form->get('urlsearch'));
echo '<div class="blockInputSearch">';
echo '<div class="blockLabel">';
echo $this->formLabel($form->get('keywordsearch'));
echo '</div>';
echo $this->formElement($form->get('keywordsearch'));
echo $this->formElementErrors($form->get('keywordsearch'));
echo '</div>';
echo $this->formLabel($form->get('default_operator'));
echo $this->formElement($form->get('default_operator'));
echo $this->formElementErrors($form->get('default_operator'));
echo '</div>';


echo '<div class="blockInputSearch left">';
echo '<div class="blockLabel">';
echo $this->formLabel($form->get('categories'));
echo '<p class="checkSpan">(<span onclick="checkCat();">check</span>/<span onclick="uncheckCat();">uncheck</span>)</p>';
echo '</div>';
echo '<div class="catBoxes">';
echo '<div class="left">';
echo $this->formElement($form->get('categories'));
echo '</div>';
echo '<div class="left">';
echo $this->formElement($form->get('categories11-20'));
echo '</div>';
echo '<div class="left">';
echo $this->formElement($form->get('categories21-30'));
echo '</div>';
echo '<div class="left">';
echo $this->formElement($form->get('categories31-40'));
echo '</div>';
echo '</div>';
echo '</div>';

//echo '<div class="blockInputSearch left">';
//echo '<div class="blockLabel">';
//echo 'Price Range ';
//echo $this->formLabel($form->get('enableSlider'));
//echo $this->formElement($form->get('enableSlider'));
//echo $this->formElementErrors($form->get('enableSlider'));
//echo '<p class="checkSpan"><input type="text" id="amount" readonly/></p>';
//echo '</div>';
//echo '<label>';
//echo '<div id="slider-range"></div></label>';
//echo '</div>';

echo '<div class="blockInputSearch bottom">';
echo $this->formButton($form->get('searchButton'));
echo '</div>';

echo $this->form()->closeTag();
?>
<p id="resultCount"></p>
<div id="results">
    <div class="page-selector" style="padding: 15px">
        <label id="pageOf" class="right" style="margin-left: 5px;"></label>
        <select class="pagesDropDown right">

        </select>
        <label class="right" style="margin-right: 5px;">Page #</label>
    </div>
    <div class="result">

    </div>
</div>
<div id="spinner" class="spinner" style="display:none;">Loading your data, give me a sec!
    <img id="img-spinner" src="/ZF2HR/public/img/ajax-loader.gif" alt="Loading"/>
</div>

<strong>Module:</strong>        Search Page &raquo;
<strong>Controller:</strong>    Index &raquo;
<strong>Action:</strong>        index
