<div class="title">
    <span class="title-text">Views per City </span>
    <img height="25" width="25" class="number-spinner" id="views-per-city-spinner" src="/img/ajax_spinner.GIF" alt="Loading"/>
</div>
<div id="views-per-city-container" class="top-margin content-container">
    <div id="views-per-city-map-container">
        <div id="views-per-city-map"> <!-- MAP -->

        </div>
    </div>

    <div id="views-per-city-table-container"> <!-- NUMBERS -->
        <label for="views-per-city-search">Find city</label>
        <input id="views-per-city-search" type="text" name="views-per-city-search">
        <table id="views-per-city-table" class="table small-table-font">
            <tr>
                <th>City</th>
                <th>Views</th>
            </tr>
        </table>
    </div>
</div>
