<h3>Views per City <img height="25" width="25" class="views-per-city-spinner" id="views-per-city-spinner" src="/img/ajax_spinner.GIF" alt="Loading"/></h3>
<div id="views-per-city" class="top-margin">
    <div id="views-per-city-map"> <!-- MAP -->

    </div>
    <div id="views-per-city-table-container"> <!-- NUMBERS -->
        <label for="views-per-city-search">Find city</label>
        <input id="views-per-city-search" type="text" name="views-per-city-search">
        <table id="views-per-city-table" class="table small-table-font">
            <tr>
                <th>City</th>
                <th>Views</th>
            </tr>
        </table>
    </div>
</div>
