<?php
$this->headLink()
        ->appendStylesheet($this->basePath() . '/css/visualization/performance/area.css')
        ->appendStylesheet($this->basePath() . '/css/visualization/performance/numbers.css')
        ->appendStylesheet($this->basePath() . '/css/visualization/performance/chartLayout.css')
        ->appendStylesheet($this->basePath() . '/css/visualization/performance/style.css')
        ->appendStylesheet($this->basePath() . '//cdn.leafletjs.com/leaflet-0.7.2/leaflet.css')
;

$this->headScript()->appendFile($this->basePath() . '/js/visualization/numbers/real-time-v2.js');
$this->headScript()->appendFile($this->basePath() . '/js/visualization/numbers/cumulative-values.js');
$this->headScript()->appendFile($this->basePath() . '/js/visualization/charts/general.js');
$this->headScript()->appendFile($this->basePath() . '/js/visualization/charts/views-over-time.js');
$this->headScript()->appendFile($this->basePath() . '/js/charts/api_charts.js');
$this->headScript()->appendFile($this->basePath() . '/js/visualization/tables/referers.js');
$this->headScript()->appendFile($this->basePath() . '/js/visualization/tables/domains.js');
$this->headScript()->appendFile($this->basePath() . '/js/visualization/multiselect.js');
$this->headScript()->appendFile($this->basePath() . '//cdn.leafletjs.com/leaflet-0.7.2/leaflet.js');
$this->headScript()->appendFile($this->basePath() . '/js/visualization/maps/views-per-city.js');
?>
<style>
    #sortable-visuals { list-style-type: none; margin: 0; padding: 0; width: auto; }
    .in-row-sortable { list-style-type: none; margin: 0; padding: 0; width: auto; }
    .in-row-sortable li { margin: 3px 3px 3px 0; padding: 1px; float: left;  }
    .ui-state-highlight { background: #99ccff; border: 2px #0033ff dotted; opacity:0.3 }
</style>

<!-- DISABLE THESE COMMENTS TO SHOW GOOGLE SPREADSHEET CHARTS ! -->
<!--<script type="text/javascript">
<?php
//if (count($this->report->getReportingKeys()) > 0) {
//    foreach ($this->report->getReportingKeys() as $key) {
//        echo "start('" . $key . "', 'visuals1');";
//    }
//}
?>
</script>-->

<h1>Revenue for <span class="bold"><?php echo $this->report->getSiteTitle(); ?></span></h1>

<div class="row">
    <?php
    echo $this->partial('partial/selects/pixels_select.phtml');
    ?>
</div>



<div id="numbers">
    <div>
        <div id="real-time-values-row" class="separate-part" style="display:none; opacity:0;">
            <?php
            echo $this->partial('partial/real-time-values/real-time-values.phtml');
            ?>
        </div>
        <div id="cumulative-values-row" class="separate-part">
            <?php
            echo $this->partial('partial/cumulative-values/cumulative-values.phtml');
            ?>
        </div>
    </div>
</div>

<div id="visuals">
    <ul id="sortable-visuals">        
        <li>
            <div class="row">
                <ul class="in-row-sortable large-sortable">
                    <li>
                        <div id="views-over-time-row" class="inline-block hide-overflow separate-part">
                            <?php echo $this->partial('partial/charts/views-over-time.phtml'); ?>
                        </div>
                    </li>
                    <li>
                        <div id="costs-row" class="inline-block hide-overflow separate-part">
                            <?php //echo $this->partial('partial/tables/device.phtml'); ?>
                            <?php echo $this->partial('partial/tables/cost.phtml'); ?>
                        </div>
                    <li>
                </ul>
            </div>

        </li>
        <li>
            <div class="row">
                <div id="per-site-data-row" class="separate-part">
                    <?php echo $this->partial('partial/tables/per-site-data.phtml'); ?>
                </div>
            </div>
        </li>
        <li>
            <div class="row">
                <ul class="in-row-sortable large-sortable">
                    <li>
                        <div id="views-per-city-row" class="inline-block hide-overflow separate-part">
                            <?php echo $this->partial('partial/maps/views-per-city.phtml'); ?>
                        </div>
                    </li>
                    <li>
                        <div id="devices-row" class="inline-block hide-overflow row-margin-left separate-part">
                            <?php echo $this->partial('partial/tables/device.phtml'); ?> 
                        </div>
                    </li>
                </ul>
            </div>
        </li>
    </ul>


    <!-- DISABLE THESE COMMENTS TO SHOW A SELECTABLE GRAPHIC CHART! -->
    <!--    <div id="selectableGraphic">
    <?php //echo $this->partial('partial/charts/selectable.phtml'); ?>
        </div> -->

    <!-- DISABLE THESE COMMENTS TO SHOW GOOGLE SPREADSHEET CHARTS ! -->
    <?php //if (count($this->report->getReportingKeys()) > 0) { ?>
    <!-- <h3>Dynamic (Self) Reporting</h3>
     <div class="graphicContainer" id="visuals1"></div> -->
    <?php
//    } else {
//        echo 'No visual information ready. If this is incorrect according to you, please contact us.';
//    }
    ?> 
</div>
<br/>
<div>
    <strong>Module:</strong>        Visualization Module &raquo;
    <strong>Controller:</strong>    Advertiser &raquo;
    <strong>Action:</strong>        revenue
</div>
