<?php
$this->headLink()
        ->appendStylesheet($this->basePath() . '/css/visualization/performance/area.css')
        ->appendStylesheet($this->basePath() . '/css/visualization/performance/chartLayout.css')
;
?>

<script type="text/javascript">
<?php
foreach ($this->report->getReportingKeys() as $key) {
    echo "start('" . $key . "', 'visuals1')";
}
?>
</script>

<h1>Revenue</h1>

<div id="numbers">
    <h2>Numbers</h2>
    <div>
        To be implemented...
    </div>
</div>

<div id="visuals">
    <h2>Visuals</h2>
    <?php if (count($this->report->getReportingKeys()) > 0) { ?>
        <div class="graphicContainer" id="visuals1"></div>
        <?php
    } else {
        echo 'No visual information ready. If this is incorrect according to you, please contact us.';
    }
    ?> 
</div>
<br/>

<strong>Module:</strong>        Visualization Module &raquo;
<strong>Controller:</strong>    Advertiser &raquo;
<strong>Action:</strong>        revenue
