<?php
$this->headLink()
        ->appendStylesheet($this->basePath() . '/css/visualization/performance/area.css')
        ->appendStylesheet($this->basePath() . '/css/visualization/performance/chartLayout.css')
;
?>

<script type="text/javascript">
    start('0AmytZLexZYpgdGpDRWVobE5XMVVtM3FTcERrbmpwWlE', 'graph1');
    start('0AmytZLexZYpgdGpDRWVobE5XMVVtM3FTcERrbmpwWlE', 'graph2');
    // start('0AmytZLexZYpgdG9lc1ZyMkppU3A2bkkzUnBMV2xEbUE', 'graph1');
    // start('0AmytZLexZYpgdEU2WHJKXzJiLU5vaXZLOGVMcGdnY3c', 'graph2');
    // start('0AmytZLexZYpgdHJIWWN5T2JNVUxKbU1HanFzdGMyMXc', 'graph3');
    // start('0AmytZLexZYpgdEY0b1QyOEJ0ajVnUU14QkRsR3FUa1E', 'graph4');
    // start('0AmytZLexZYpgdFIwYlNicWZ5OEQ0VTh2cF84dllwaXc', 'graph5');
</script>




<div class="graphicContainer" id="graph1">

</div>
<div class="graphicContainer" id="graph2">

</div>

<strong>Module:</strong>        Visualization Module &raquo;
<strong>Controller:</strong>    Advertiser &raquo;
<strong>Action:</strong>        revenue
