<?php
$this->headScript()->appendFile($this->basePath() . '/js/real-time/testing.js');
?>

<div>
    <input type="text" name="dimensions" id="dimensions" style="width: 400px" placeholder="dimensions">
    <input type="text" name="measures" id="measures" style="width: 400px" placeholder="measures">
    <input type="button" id="submit" value="Submit">
    <br/>
    <br/>
    <textarea id="output">
        
    </textarea>
</div>


<div>
    <strong>Module:</strong>        Visualization Module &raquo;
    <strong>Controller:</strong>    Advertiser &raquo;
    <strong>Action:</strong>        revenue
</div>
