<?php
$this->headScript()->appendFile($this->basePath() . '/js/real-time/testing.js');
?>

<div>
    <input type="text" name="method" id="method" style="width: 400px" placeholder="Method">
    <input type="text" name="methodParameters" id="methodParameters" style="width: 400px" placeholder="Method Parameters">
    <input type="text" name="siteIds" id="beaconIds" style="width: 400px" placeholder="siteIds">
    <input type="button" id="submit" value="Submit">
    <br/>
    <br/>
    <textarea id="output">
        
    </textarea>
</div>


<div>
    <strong>Module:</strong>        Visualization Module &raquo;
    <strong>Controller:</strong>    Advertiser &raquo;
    <strong>Action:</strong>        revenue
</div>
