<h3>Select your Pixels</h3>
<select multiple="multiple" id="publisher_select">
    <?php
    foreach ($this->sites as $site) {

        echo '<option selected="selected" value="' . $site["idsite"] . '">' . $site["name"] . '</option>';
    }
    ?>
</select>
<select multiple="multiple" id="campaign_select">
    <?php
    foreach ($this->sites as $site) {

        echo '<option selected="selected" value="' . $site["idsite"] . '">' . $site["name"] . '</option>';
    }
    ?>
</select>
<select multiple="multiple" id="beacon_select">
    <?php
    foreach ($this->sites as $site) {

        echo '<option selected="selected" value="' . $site["idsite"] . '">' . $site["name"] . '</option>';
    }
    ?>
</select>