<?php
$this->headLink()
        ->appendStylesheet($this->basePath() . '/css/performance/area.css');
?>

<div id="spinner" class="spinner" style="display:block;">Loading your data, give me a sec!
    <img id="img-spinner" src="/ZF2HR/public/img/ajax-loader.gif" alt="Loading"/>
</div>
<div id="main-wrapper">
    <div id="performance" class="toggleable on">
        <div id="header">
            <div class="right"><a href="http://www.sap.com/" class="twitter-share-button" ><img src="http://www.sap.com/content/sapcom/global/usa/en_us/_jcr_content/headerLogo/image.img.png"></a></div>

            <center><h1>Performance PR campaigns</h1></center>
            <p>Hieronder is de performance te zien per gevoerde campagne en per publisher. Alle publicaties van dezelfde publishers zijn geaccumuleerd. Indien de tracking pixel geplaatst wordt zijn we in staat om onderstaande data makkelijk te genereren. Momenteel betreft dit dummy data aangezien er geen data is uit het verleden.  </strong></p>
            <div class="clr"></div>
        </div>
        <div id="graphics">
            <div id="coveragePillars1"></div>
            <div id="coveragePillars2"></div>
        </div>



    </div>

</div>


<strong>Module:</strong>        Performance &raquo;
<strong>Controller:</strong>    Index &raquo;
<strong>Action:</strong>        index

<script type="text/javascript">
    loadDataDynamically('0AmytZLexZYpgdGRXVXZ5cDYtT09LOXBGX3hJbzNGOFE', 'coveragePillars2');
    loadDataDynamically('0AmytZLexZYpgdGVLVzBPWms3aVB2dWtZZVl3QndEOWc', 'coveragePillars1');
    loadDataDynamically('0AmytZLexZYpgdGpqV2FqRzZqSDM2RUxKc191YXBTeUE', 'testDateTime');
</script>