<?php
$this->headLink()
        ->appendStylesheet($this->basePath() . '/css/performance/area.css');
?>

<div id="spinner" class="spinner" style="display:block;">Loading your data, give me a sec!
    <img id="img-spinner" src="/ZF2HR/public/img/ajax-loader.gif" alt="Loading"/>
</div>
<div class="jumbotron">
    <h1>Performance</h1>
    <p>Performance reports & statistics</p>
    <p class="btn btn-success btn-lg">Link to some information</p>
    <p class="btn btn-success btn-lg">Link to some more information</p>
    <p class="btn btn-success btn-lg">Link to even more information!</p>
</div>
<div id="graphics">
    <div id="experimental"></div>
    <div id="coveragePillars1"></div>
    <div id="coveragePillars2"></div>
</div>





<strong>Module:</strong>        Performance &raquo;
<strong>Controller:</strong>    Index &raquo;
<strong>Action:</strong>        index

<script type="text/javascript">
    loadDataDynamically('0AmytZLexZYpgdElTSF9FbDFhWW5kUXprY3RDeEowcmc', 'experimental');
    loadDataDynamically('0AmytZLexZYpgdGRXVXZ5cDYtT09LOXBGX3hJbzNGOFE', 'coveragePillars2');
    loadDataDynamically('0AmytZLexZYpgdGVLVzBPWms3aVB2dWtZZVl3QndEOWc', 'coveragePillars1');
    loadDataDynamically('0AmytZLexZYpgdGpqV2FqRzZqSDM2RUxKc191YXBTeUE', 'testDateTime');
</script>