<?php
$this->headLink()
        ->appendStylesheet($this->basePath() . '/css/search/form.css')
        ->appendStylesheet($this->basePath() . '/css/search/results.css');
$this->headScript()
        ->appendFile($this->basePath() . '/js/search/search.js');
$title = "Search for publishers";
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
echo $this->form()->openTag($form);

echo $this->partial('partial/search-block.phtml', array('form' => $form));

echo $this->form()->closeTag();
?>

<div id="results">
    <p id="resultCount" class="left"></p>
    <div class="page-selector" style="padding: 15px">

        <label id="pageOf" class="right" style="margin-left: 5px;"></label>
        <select class="pagesDropDown right">

        </select>
        <label class="right" style="margin-right: 5px;">Page #</label>
    </div>
    <div class="result">

    </div>
</div>



<strong>Module:</strong>        Search Module &raquo;
<strong>Controller:</strong>    Advertiser &raquo;
<strong>Action:</strong>        index
