<?php
$this->headLink()
        ->appendStylesheet($this->basePath() . '/css/visualization/style.css');
$title = "Visualization - Get insights into your data!";
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<ul class="menu-page">
    <li class="menu-page-item">
        <div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->translate('Bounce-back insights') ?></h3>
                </div>
                <div class="panel-body">
                    <p><?php echo sprintf($this->translate('Collaboration between publishers and advertisers could not have been easier with PubNext, where these parties are intermittently brought together by smart algorithms. A perfect match between advertisers and publishers could result in profit for both. So why not get started right away?'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                    <p><a class="btn btn-success pull-right" href="link-to-bounceback-insights"><?php echo $this->translate('Go!') ?> &raquo;</a></p>
                </div>
            </div>
        </div>
    </li>
    <li class="menu-page-item">
        <div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->translate('Revenue') ?></h3>
                </div>
                <div class="panel-body">
                    <p><?php echo sprintf($this->translate('Collaboration between publishers and advertisers could not have been easier with PubNext, where these parties are intermittently brought together by smart algorithms. A perfect match between advertisers and publishers could result in profit for both. So why not get started right away?'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                    <p><a class="btn btn-success pull-right" href="link-to-revenue"><?php echo $this->translate('Go!') ?> &raquo;</a></p>
                </div>
            </div>
        </div>
    </li>
    <li class="menu-page-item">
        <div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->translate('General Information') ?></h3>
                </div>
                <div class="panel-body">
                    <p><?php echo sprintf($this->translate('Collaboration between publishers and advertisers could not have been easier with PubNext, where these parties are intermittently brought together by smart algorithms. A perfect match between advertisers and publishers could result in profit for both. So why not get started right away?'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                    <p><a class="btn btn-success pull-right" href="link-to-general-information"><?php echo $this->translate('Go!') ?> &raquo;</a></p>
                </div>
            </div>
        </div>
    </li>
    <li class="menu-page-item">
        <div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->translate('More Information') ?></h3>
                </div>
                <div class="panel-body">
                    <p><?php echo sprintf($this->translate('Collaboration between publishers and advertisers could not have been easier with PubNext, where these parties are intermittently brought together by smart algorithms. A perfect match between advertisers and publishers could result in profit for both. So why not get started right away?'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                    <p><a class="btn btn-success pull-right" href="link-to-some-more-information"><?php echo $this->translate('Go!') ?> &raquo;</a></p>
                </div>
            </div>
        </div>
    </li>
    <!--    <li class="menu-page-item">This is the 2nd of many!</li>
        <li class="menu-page-item">This is the 3rd of many!</li>
        <li class="menu-page-item">This is the 4th of many!</li>
        <li class="menu-page-item">This is the 5th of many!</li>
        <li class="menu-page-item">This is the 6th of many!</li>
        <li class="menu-page-item">This is the 7th of many!</li>-->
</ul>



<strong>Module:</strong>        Visualization Module &raquo;
<strong>Controller:</strong>    Publisher &raquo;
<strong>Action:</strong>        index
