<h3>Campaign Costs<img height="25" width="25" class="number-spinner" id="cost-campaign-spinner" src="/img/ajax_spinner.GIF" alt="Loading"/></h3>
<div class="top-margin">
    <table class="table small-table-font">
        <tr>
            <th>Advertising Campaign</th>
            <th>Cost per 1.000 views</th> 
            <th>Cost per 1.000 users</th>
        </tr>
        <tr>
            <td>Campaign 1</td>
            <td>$0.02</td>
            <td>$0.05</td>
        </tr>
    </table>
</div>