<?php $this->headScript()->appendFile($this->basePath() . '/js/visualization/tables/cost.js'); ?>
<div class="title">
    <span class="title-text">To Be Determined Data </span>
    <img height="25" width="25" class="number-spinner" id="tbd-spinner" src="/img/ajax_spinner.GIF" alt="Loading"/>
</div>
<div id="cost" class="content-container">
    <div id="cost-tabs">
        <ul>            
            <li><a href="#pixel-1">Pixel Costs <img height="25" width="25" class="number-spinner" id="cost-pixel-spinner" src="/img/ajax_spinner.GIF" alt="Loading"/></a></li>
            <li><a href="#campaign-1">Campaign Costs <img height="25" width="25" class="number-spinner" id="cost-campaign-spinner" src="/img/ajax_spinner.GIF" alt="Loading"/></a></li>
        </ul>
        <div id="pixel-1">
            <?php echo $this->partial('partial/tables/cost-pixel.phtml'); ?>
        </div>
        <div id="campaign-1">
            <?php echo $this->partial('partial/tables/cost-campaign.phtml'); ?>
        </div>

    </div>
</div>