<h3>Custom Groups</h3>
<div id="on-page-custom-group" class="top-margin">
    <label for="custom-group-search">Find group</label>
    <input id="custom-group-search" type="text" name="custom-group-search">
    <table id="custom-group-table" class="table small-table-font">
        <tr>
            <th>Group Name</th>
            <th>Group Type</th>
            <th>Unique Users</th>
            <th>Views</th>
            <th>Form Clicks</th>
            <th>Avg Time on Article (s)</th>
        </tr>
    </table>
</div>