<div id="devices-container">
    <h3>Cumulatives per Device <img height="25" width="25" class="number-spinner" id="device-table-spinner" src="/img/ajax_spinner.GIF" alt="Loading"/></h3>
    <div class="top-margin">
        <table class="table">
            <tr>
                <th></th>
                <th>PC/Laptop</th>
                <th>Tablet</th>
                <th>Mobile</th>
            </tr>
            <tr>
                <td><b>Total Views</b></td>
                <td id="pc-views">???</td>
                <td id="tablet-views">???</td>
                <td id="mobile-views">???</td>
            </tr>
            <tr>
                <td><b>Clicks</b></td>
                <td id="pc-clicks">???</td>
                <td id="tablet-clicks">???</td>
                <td id="mobile-clicks">???</td>
            </tr>
            <tr>
                <td><b>Unique Users</b></td>
                <td id="pc-users">???</td>
                <td id="tablet-users">???</td>
                <td id="mobile-users">???</td>
            </tr>
            <tr>
                <td><b>Avg. Time on Site</b></td>
                <td id="pc-time">???</td>
                <td id="tablet-time">???</td>
                <td id="mobile-time">???</td>
            </tr>
        </table>
    </div>
</div>