<h3>Domains <img height="25" width="25" class="domains-spinner" id="domains-spinner" src="/img/ajax_spinner.GIF" alt="Loading"/></h3>
<div id="domains" class="top-margin">
    <label for="domains-search">Find domain</label>
    <input id="domains-search" type="text" name="domains-search">
    <table id="domains-table" class="table">
        <tr>
            <th>Domain</th>
            <th>Views</th>
        </tr>
    </table>
</div>