<h3>Domains</h3>
<div id="domains" class="top-margin">
    <label for="domains-search">Find domain</label>
    <input id="domains-search" type="text" name="domains-search">
    <table id="domains-table" class="table small-table-font">
        <tr>
            <th>Referer URL</th>
            <th>Unique Users</th>
            <th>Views</th>
            <th>Form Clicks</th>
            <th>Avg Time on Article (s)</th>
        </tr>
    </table>
</div>