<?php $this->headScript()->appendFile($this->basePath() . '/js/visualization/tables/per-site-data.js'); ?>
<h3>On Page Data</h3>
<div id="per-site">
    <div id="dialog" title="Tab data">
        <form>
            <fieldset class="ui-helper-reset">
                <label for="tab_title">Title</label>
                <input type="text" name="tab_title" id="tab_title" value="" class="ui-widget-content ui-corner-all">
                <label for="tab_content">Content</label>
                <textarea name="tab_content" id="tab_content" class="ui-widget-content ui-corner-all"></textarea>
            </fieldset>
        </form>
    </div>

    <div id="per-site-tabs">
        <ul>
            <li><a href="#referers-1">Referers <img height="25" width="25" class="number-spinner" id="referers-spinner" src="/img/ajax_spinner.GIF" alt="Loading"/></a></li>
            <li><a href="#domains-1">Domains <img height="25" width="25" class="domains-spinner" id="domains-spinner" src="/img/ajax_spinner.GIF" alt="Loading"/></a></li>
            <li class="rightTab"><button id="add_tab">Add Group</button></li>
        </ul>
        <div id="referers-1">
            <?php echo $this->partial('partial/tables/referers.phtml'); ?>
        </div>
        <div id="domains-1">
            <?php echo $this->partial('partial/tables/domains.phtml'); ?>
        </div>

    </div>
</div>
