<h3>Referers <img height="25" width="25" class="number-spinner" id="referers-spinner" src="/img/ajax_spinner.GIF" alt="Loading"/></h3>
<div id="referers" class="top-margin">
    <label for="referers-search">Find referer</label>
    <input id="referers-search" type="text" name="referers-search">
    <table id="referers-table" class="table">
        <tr>
            <th>Referer URL</th>
            <th>Views</th>
        </tr>
    </table>
</div>