<h3>Referers</h3>
<div id="referers" class="top-margin">
    <label for="referers-search">Find referer</label>
    <input id="referers-search" type="text" name="referers-search">
    <table id="referers-table" class="table small-table-font">
        <tr>
            <th>Referer URL</th>
            <th>Unique Users</th>
            <th>Views</th>
            <th>Form Clicks</th>
            <th>Avg Time on Article (s)</th>
        </tr>
    </table>
</div>