<h3>Referers</h3>
<div id="referers" class="top-margin">
    <label for="referers-search">Find referer</label>
    <input id="referers-search" type="text" name="referers-search">
    <table id="referers-table" class="table small-table-font">
        <tr>
            <th><input type="checkbox" id="selectAllReferers"></th>
            <th class="largeHeader">Referer URL</th>
            <th class="smallHeader">Unique Users</th>
            <th class="smallHeader">Visits</th>
            <th class="smallHeader">Actions</th>
            <th class="smallHeader">Bounce Count</th>
        </tr>
    </table>
</div>