<h3>Views per Article <img height="25" width="25" class="number-spinner" id="views-per-article-spinner" src="/img/ajax_spinner.GIF" alt="Loading"/></h3>
<div class="top-margin">
    <table class="table">
        <tr>
            <th>Domain</th>
            <th>Pixel</th>
            <th>Tablet</th>
            <th>Mobile</th>
        </tr>
        <tr>
            <td><b>Total Views</b></td>
            <td id="pc-views">???</td>
            <td id="tablet-views">???</td>
            <td id="mobile-views">???</td>
        </tr>
        <tr>
            <td><b>Clicks</b></td>
            <td id="pc-clicks">???</td>
            <td id="tablet-clicks">???</td>
            <td id="mobile-clicks">???</td>
        </tr>
        <tr>
            <td><b>Unique Users</b></td>
            <td id="pc-users">???</td>
            <td id="tablet-users">???</td>
            <td id="mobile-users">???</td>
        </tr>
        <tr>
            <td><b>Avg. Time on Site</b></td>
            <td id="pc-time">???</td>
            <td id="tablet-time">???</td>
            <td id="mobile-time">???</td>
        </tr>
    </table>
</div>