<div id="sidebar-wrapper">

    <?php echo $this->navigation('sidebar_navigation')->menu()->setUlClass('sidebar-nav sidenavbar-nav sidebar-nav-bot'); ?>

    <ul class="sidebar-nav sidenavbar-nav sidebar-nav-bot bottomSidebar">
        <li id="lockSidebar"><a href="#">Lock Sidebar  <span id="lockIcon" class="" style="color:#FFF;"></span></a></li>
        <li><a class="logout" href="user/logout">Logout</a></li>
    </ul>

</div>