<div class="blockId">
    <div id="impressions">
        <div class="actualNumber">
            <div class="numberType">
                <div class="numberTitleBlock">
                    <span class="numberTitle centerText">Total Views</span>
                </div>
                <div>
                    <span id="pixel_count" class="number centerText">
                        <?php
                        echo $pixels;
                        ?>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="blockId">
    <div id="pixels">
        <div class="actualNumber">
            <div class="numberType">
                <div class="numberTitleBlock">
                    <span class="numberTitle centerText">Unique Users</span>
                </div>
                <div>
                    <span id="unique_user_count" class="number centerText">
                        <?php
                        echo $pixels;
                        ?>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="blockId">
    <div id="impressions_bid">
        <div class="actualNumber">
            <div class="numberType">
                <div class="numberTitleBlock">
                    <span class="numberTitle centerText">Average Time on Site</span>
                </div>
                <div>
                    <span id="imp_bid_count" class="number centerText">
                        <?php
                        echo $pixels;
                        ?>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="blockId">
    <div id="click">
        <div class="actualNumber">
            <div class="numberType">
                <div class="numberTitleBlock">
                    <span class="numberTitle centerText">Bounce Rate (%)</span>
                </div>
                <div>
                    <span id="click_count" class="number centerText">
                        <?php
                        echo $pixels;
                        ?>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>