<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="robots" content="noindex">
        <?php echo $this->headTitle('PN ' . $this->translate('PubNxt'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/tipsy.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/highslide.css')
                ->prependStylesheet($this->basePath() . '/css/navigation/sidebar.css')
                ->prependStylesheet($this->basePath() . '/css/loadingAnimation/loading.css')
                ->prependStylesheet($this->basePath() . '/css/jquery.multiselect.filter.css')
                ->prependStylesheet($this->basePath() . '/css/jquery.multiselect.css')
                ->prependStylesheet($this->basePath() . '//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootbox.min.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile($this->basePath() . '/js/navigation/user-control.js')
                ->appendFile($this->basePath() . '/js/navigation/sidebar.js')
                //->appendFile($this->basePath() . '//code.highcharts.com/stock/highstock.src.js')
                ->appendFile($this->basePath() . '/js/highstock.js')
                ->appendFile($this->basePath() . '//code.highcharts.com/modules/exporting.js')
                ->appendFile($this->basePath() . '/js/charts/engine_v2.js')
                ->appendFile($this->basePath() . '//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js')
                ->appendFile($this->basePath() . '/js/jquery.multiselect.min.js')
                ->appendFile($this->basePath() . '/js/jquery.multiselect.filter.js')
                ->appendFile($this->basePath() . '/js/jquery.tipsy.js')
                ->appendFile($this->basePath() . '/js/highslide.js')
        ;
        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/PNLogo.png') ?>" alt="PubNxt"/>&nbsp;<?php echo $this->translate('PubNxt') ?></a>
                </div>
                <div class="collapse navbar-collapse">

                    <?php
                    echo $this->navigation('main_navigation')
                            ->menu()
                            ->setMinDepth(0)
                            ->setMaxDepth(0)
                            ->setUlClass('nav navbar-nav')
                            ->render();

                    if ($this->role !== null) {
                        echo $this->navigation($this->role->getRoleId() . '_navigation')
                                ->menu()
                                ->setMinDepth(0)
                                ->setMaxDepth(0)
                                ->setUlClass('nav navbar-nav')
                                ->render();
                    }
                    echo $this->navigation('user_navigation')
                            ->menu()
                            ->setMinDepth(0)
                            ->setMaxDepth(0)
                            ->setUlClass('nav navbar-nav')
                            ->render();
                    if ($this->role !== null) {
                        echo '<input type="hidden" value="' . $this->role->getRoleId() . '" id="roleVar">';
                        echo $this->partial('partial/user-info/user-info.phtml');
                    }
                    ?>

                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container wrapper">
            <div id="spinner" class="spinner" style="display:none">Loading your data, give me a sec!
                <img id="img-spinner" src="/img/ajax-loader.gif" alt="Loading"/>
            </div>
            <?php
            if ($this->role !== null) {
                echo $this->partial('partial/sidebar/sidebar.phtml');
            }

            echo $this->content;
            ?>

            <hr>
            <footer>
                <p>&copy; 2012 - <?php echo date('Y') ?> by SourceRepublic. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>

    </body>
</html>
