<div>
    <h2>Cumulative Values  <img height="25" width="25" class="number-spinner" id="cumulative-values-spinner" src="/img/ajax_spinner.GIF" alt="Loading"/></h2>
</div>
<div id="cumulative-values" class="hide-overflow">

    <div id="spinner" style="">

    </div>
    <div class="blockId">
        <div id="impressions">
            <div class="actualNumber">
                <div class="numberType">
                    <div class="numberTitleBlock">
                        <span class="font-icon glyphicon glyphicon-eye-open centerText" style="color:#0066FF;"></span><br/>
                        <span class="numberTitle centerText">Total Pixel Views</span>
                    </div>
                    <div>
                        <span id="total_view_count" class="number centerText">
                            <?php
                            echo 0; //$this->total_views;
                            ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="blockId">
        <div id="pixels">
            <div class="actualNumber">
                <div class="numberType">
                    <div class="numberTitleBlock">
                        <span  class="font-icon  glyphicon glyphicon-user centerText" style="color:#0066FF;"></span><br/>
                        <span class="numberTitle centerText">Unique Users</span>
                    </div>
                    <div>
                        <span id="unique_user_count" class="number centerText">
                            <?php
                            echo $this->unique_users;
                            ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="blockId">
        <div id="impressions_bid">
            <div class="actualNumber">
                <div class="numberType">
                    <div class="numberTitleBlock">
                        <span class="font-icon  glyphicon glyphicon-time centerText" style="color:#0066FF;"></span><br/>
                        <span class="numberTitle centerText">Average Time on Article (in seconds)</span>
                    </div>
                    <div>
                        <span id="avg_time_on_site" class="number centerText">
                            <?php
                            echo $pixels;
                            ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="blockId">
        <div id="click">
            <div class="actualNumber">
                <div class="numberType">
                    <div class="numberTitleBlock">
                        <span  class="font-icon glyphicon glyphicon-eye-close centerText" style="color:#0066FF;"></span><br/>
                        <span class="numberTitle centerText">Bounce Rate (%)</span>
                    </div>
                    <div>
                        <span id="click_count" class="numSber centerText">
                            <?php
                            echo '0 <span height="10" width="10" class="font-icon glyphicon glyphicon-exclamation-sign centerText" style="color:red;"></span>'; //"Not Implemented";
                            ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
