<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('SourceRepublic Dashboard'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Dynamic reporting overview'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="performance"><?php echo $this->translate('More in-depth statistics') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Chart 1') ?></h3>
            </div>
            <div class="panel-body">

                <div id="highroller2"></div>
                <?php
                $this->highroller2->chart->renderTo = "highroller2";
                $this->headScript()->appendScript($this->highroller2->renderChart());
                ?>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Chart 2') ?></h3>
            </div>
            <div class="panel-body">
                <div id="highroller"></div>
                <?php
                $this->highroller->chart->renderTo = "highroller";
                $this->headScript()->appendScript($this->highroller->renderChart());
                ?>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <div id="highroller3"></div>
                <?php
                $this->highroller3->chart->renderTo = "highroller3";
                $this->headScript()->appendScript($this->highroller3->renderChart());
                ?>
            </div>
        </div>
    </div>
</div>
